-- Create company_types table
create table public.company_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert default types
insert into public.company_types (name) values
  ('Robotics Company'),
  ('Integrator'),
  ('Component Supplier'),
  ('Service Provider'),
  ('Startup'),
  ('Other');

-- Create companies table
create table public.companies (
  id bigint generated by default as identity primary key,
  name text not null,
  logo_url text,
  description text,
  website_url text,
  email text,
  phone text,
  address text,
  city text,
  state text,
  country text default 'India',
  founded_year integer,
  employee_count text,
  primary_type_id bigint references public.company_types(id),
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.companies enable row level security;
alter table public.company_types enable row level security;

-- Create policies
create policy "Enable read access for all users" on public.companies for select using (true);
create policy "Enable read access for all users" on public.company_types for select using (true);

-- Allow write access only to authenticated users
create policy "Enable insert for authenticated users only" on public.companies for insert with check (auth.role() = 'authenticated');
create policy "Enable update for service_role" on public.companies for update using (true);
