-- Create robotics_news table
create type public.news_country_focus as enum ('India', 'China', 'Both', 'Global');
create type public.news_category as enum ('Industrial', 'Humanoid', 'Defense', 'Warehouse', 'AI', 'Policy', 'Funding');
create type public.news_status as enum ('Draft', 'Published', 'Archived');

create table public.robotics_news (
  id bigint generated by default as identity primary key,
  headline text not null,
  slug text not null unique,
  summary text,
  article_body text,
  country_focus public.news_country_focus default 'Global',
  category public.news_category default 'Industrial',
  strategic_importance integer check (strategic_importance >= 0 and strategic_importance <= 5),
  relevance_score integer check (relevance_score >= 0 and relevance_score <= 5),
  credibility_score integer check (credibility_score >= 0 and credibility_score <= 5),
  recency_score integer check (recency_score >= 0 and recency_score <= 5),
  total_score integer generated always as (relevance_score + strategic_importance + credibility_score + recency_score) stored,
  source_name text,
  source_url text,
  seo_keywords text[],
  published_date timestamp with time zone default timezone('utc'::text, now()) not null,
  status public.news_status default 'Draft',
  confidence_score integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.robotics_news enable row level security;

-- Policies
create policy "Enable read access for all users" on public.robotics_news for select using (status = 'Published');
create policy "Enable insert for authenticated users only" on public.robotics_news for insert with check (auth.role() = 'authenticated');
create policy "Enable update for authenticated users only" on public.robotics_news for update using (auth.role() = 'authenticated');
